# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e3a6393b689cabff2c57a060c0889710c236b3a6d8bf25078d50e302eb548346fd37e2c8f4099e7c95488da36492d7b0f4a4455fef2bc83adb3ab1675bee6c0

test:
  secret_key_base: 8bb94fbff178b6f25f60a07f38d6192f2a3a5cb72cae370de379c3425a19520be1fed8343706665d1bd06ba80c3325c627b1f34e8df9604e8c9696960f652ee2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
